---
language: ruby

gemfile:
  - Gemfile

before_install:
  - gem update --system -N
  - gem install bundler -N

services:
  - redis

addons:
  apt:
    packages:
      - chromium-browser

cache:
  bundler: true
  directories:
    - ~/.webdrivers

notifications:
  email:
    on_success: never
    on_failure: change

script: bundle exec rake $RAKE_TASK

matrix:
  include:
    - rvm: 3.0
      gemfile: Gemfile
      env: RAKE_TASK=spec
    - rvm: 2.7
      gemfile: Gemfile
      env: RAKE_TASK=spec
    - rvm: 2.6
      gemfile: Gemfile
      env: RAKE_TASK=spec
