---
language: ruby
rvm:
  - 2.7.2
  - 2.6.6
gemfile:
  - Gemfile

before_install:
  - gem update --system -N
  - gem install bundler -N

addons:
  apt:
    packages:
      - chromium-browser

cache:
  bundler: true
  directories:
    - ~/.webdrivers

notifications:
  email:
    on_success: never
    on_failure: change

script: bundle exec rake $RAKE_TASK

matrix:
  include:
    - rvm: 2.7
      env: RAKE_TASK=spec
    - rvm: 2.6
      env: RAKE_TASK=spec
